language: python

python: "2.7"

install:
    - pip install setuptools==7.0 --ignore-installed
    - cp buildout/* .
    - mkdir -p buildout-cache/eggs
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg --setuptools-version 7.0
    - bin/buildout -N -t 3 -v -c travis.cfg

script: bin/coverage run bin/test -s seantis.people

after_success:
    - pip install coveralls
    - coveralls

cache:
    directories:
        - buildout-cache/eggs
